name: Build Windows
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: jlink
        run: mvn javafx:jlink
      - name: jpackage
        run: |
          jpackage `
            --runtime-image target/app `
            --name VideoAdapter `
            --module com.alexuva.app.videoadapter/com.alexuva.app.videoadapter.VideoAdapterApplication `
            --type app-image `
            --dest output/ `
            --verbose
      - name: Zip app-image
        run: Compress-Archive -Path output/VideoAdapter -DestinationPath output/VideoAdapter-windows.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/VideoAdapter-windows.zip